"""Public imports for shared learning definitions."""
from game2.v2.learning.config import (
    POLICY_STRIDE_TICKS,
    PPO_TAIL_TICKS,
    PPO_HISTORY_STRIDE_TICKS,
    MAX_EPISODE_DATASETS,
    CONTROL_CHANGE_PENALTY,
    PPO_GAMMA,
    PPO_GAE_LAMBDA,
    PPO_CLIP_EPS,
    PPO_EPOCHS,
    PPO_BATCH_SIZE,
    PPO_ENTROPY_COEF,
    PPO_VALUE_COEF,
    PPO_MAX_GRAD_NORM,
    PPO_LEARNING_RATE,
)

__all__ = [
    "POLICY_STRIDE_TICKS",
    "PPO_TAIL_TICKS",
    "PPO_HISTORY_STRIDE_TICKS",
    "MAX_EPISODE_DATASETS",
    "CONTROL_CHANGE_PENALTY",
    "PPO_GAMMA",
    "PPO_GAE_LAMBDA",
    "PPO_CLIP_EPS",
    "PPO_EPOCHS",
    "PPO_BATCH_SIZE",
    "PPO_ENTROPY_COEF",
    "PPO_VALUE_COEF",
    "PPO_MAX_GRAD_NORM",
    "PPO_LEARNING_RATE",
]
